version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}

  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: ${POSTGRES_DBNAME}
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASS}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASS}
      ports:
        - 8080:8080
      depends_on:
        - postgres